### ISSUE TITLE
Popup about time limit continuously opens 

### ISSUE THREAD

**Issue by googol42** [revager-org/revager#10]
How to reproduce?

1. Set the maximal time a meeting can last to the lowest possible time.
2. Wait until the time is elapsed.

Expected behaviour: A single popup opens to indicate that the time has elapsed.

Observed behaviour: Each second the said popup opens.

Workaround: Press ESC to close all popups. Once all popups are closed no new popup opens.

Bug is in FindingsListFrame#updateClock. The flag should be set before displaying the popup.

**Comment by kuleszdl** [comment]
Patches welcome
